"""Tests for ORM model instantiation — no DB required."""

import uuid
import pytest
from models.task import Task, TaskConfig
from models.document import SourceDocument, ParsedDocument
from models.section import Section, SectionVersion
from models.review import ReviewResultModel, ReviewIssueModel
from models.knowledge import Rule, TerminologyEntry, KnowledgeChunk


def test_task_instantiation():
    """Task model can be instantiated with required fields."""
    task = Task(name="Test Report", doc_type="report")
    assert task.name == "Test Report"
    assert task.doc_type == "report"


def test_section_instantiation():
    """Section model can be instantiated with required fields."""
    task_id = uuid.uuid4()
    section = Section(task_id=task_id, title="Introduction", level=1, order_index=0)
    assert section.title == "Introduction"
    assert section.level == 1


def test_review_result_model_instantiation():
    """ReviewResultModel can be instantiated."""
    task_id = uuid.uuid4()
    result = ReviewResultModel(
        task_id=task_id, round_number=1, reviewer_name="structure_reviewer"
    )
    assert result.reviewer_name == "structure_reviewer"


def test_knowledge_chunk_instantiation():
    """KnowledgeChunk model can be instantiated with vector field."""
    chunk = KnowledgeChunk(content="Some knowledge text")
    assert chunk.content == "Some knowledge text"
    assert chunk.embedding is None  # nullable


def test_all_models_importable():
    """All models in __init__ are importable without error."""
    from models import (
        Base,
        Task,
        TaskConfig,
        SourceDocument,
        ParsedDocument,
        Section,
        SectionVersion,
        ReviewResultModel,
        ReviewIssueModel,
        Rule,
        TerminologyEntry,
        KnowledgeChunk,
        UserComment,
        ExportArtifact,
        DocumentTemplate,
        AuditEntry,
    )

    assert Base is not None
    assert Task is not None


def test_task_has_uuid_default():
    """Task.id has UUID type."""
    task = Task(name="Test", doc_type="report")
    # id is generated by default= on the column — no explicit assignment needed
    assert task.id is None or isinstance(task.id, uuid.UUID)
